name: Push to github container register

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: push-docker
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install k3s
      run: |
        curl -sfL https://get.k3s.io | sh -
        sudo chmod -R a+rw /etc/rancher/k3s
        sudo mkdir -p $HOME/.kube && sudo chown -R runner $HOME/.kube
        sudo k3s kubectl config view --raw > $HOME/.kube/config
        sudo chown runner $HOME/.kube/config
        sudo chmod go-r $HOME/.kube/config
        kubectl version
    - name: Deploy cloud shell
      run: |
        kubectl create namespace shell
        kubectl apply -f manifests
        while true; do
            ready=$(kubectl -n shell get deployment $deployment -o jsonpath='{.status.readyReplicas}')
            desired=$(kubectl -n shell get deployment $deployment -o jsonpath='{.spec.replicas}')
            if [ "$ready" == "$desired" ]; then
               echo "Deployment $deployment is ready!"
               exit 0
            fi
            sleep 5
        done
        echo "Ok"
        kubectl port-forward -n shell svc/cloud-shell-service 8000:8000
        sleep 5
    - name: Run E2E test
      run: |
        pip install websockets
        python3 tests/basic.py
